language: go
sudo: required
go:
   - 1.6
   - 1.7
   - 1.8
   - 1.9
   - tip
before_install:
  - sudo apt-get update
  - sudo apt-get install -y dnsutils

script:
  - go get -v -u github.com/vinsonzou/gohttpdns
  - gohttpdns -bind "127.0.0.1:8053" &
  - sleep 0.1
  - dig +short @127.0.0.1 -p 8053 google.com
  - dig +short @127.0.0.1 -p 8053 Qq.com
